#!/bin/python
#coding:utf-8

model_params={
    'LR_run':{
        'penalty':'l2',
        'tol':0.0001,
        'max_iter':100
    },
    'SVC_run':{
        'C':0.8,
        'kernel':'rbf',
        'tol':0.0001
    },
    'RF_run':{
        'n_estimators':500,
        'max_depth':6,
        'criterion':'entropy',
        'min_samples_split':2,
        'min_samples_leaf':2
    },
    'XGB_run':{
        'learning_rate':0.02,
        'max_depth':7,
        'num_boost_round':150,
        'objective': 'binary:logistic',
        'min_child_weight':1,
        'scale_pos_weight':1,
        'gamma':0,
        'lambda':0.5,
        'alpha':0.5,
        'eval_metric':'auc'
    }
}
